name: uihub_facebook_home
description: "facebook home ui clone for flutter uihub"
#publish_to: 'none'
repository: https://github.com/flutter-uihub/uihub_facebook_home

version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  styled_widget:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  assets:
    - assets/uihub/uihub_facebook_home/
  uses-material-design: true

topics:
  - uihub